exports.createNewArticle = async(req, res, next) => {
    try {
        
    } 
    catch (error) {
        next(error);
        return res.status(500).json({message: "We have error in Article Controller"})    
    }
}

exports.getAll = async(req, res, next) => {
    try {
        
    } 
    catch (error) {
        next(error);
        return res.status(500).json({message: "We have error in Article Controller"})    
    }
}

exports.getOneArticle = async(req, res, next) => {
    try {
        
    } 
    catch (error) {
        next(error);
        return res.status(500).json({message: "We have error in Article Controller"})    
    }
}

exports.removeArticle = async(req, res, next) => {
    try {
        
    } 
    catch (error) {
        next(error);
        return res.status(500).json({message: "We have error in Article Controller"})    
    }
}